name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  - master
resources:
  repositories:
    - repository: self
  containers:
    - container: tooling_tester
      image: terraformation/tooling-tester
pool:
  vmImage: 'ubuntu-latest'
container: tooling_tester
variables:
  GO_CACHE_FOLDER: $(Build.SourcesDirectory)/src/tests/vendor
steps:
  - download: none
  - task: Cache@2
    inputs:
      key: 'v1| go | "$(Agent.OS)" | $(Build.SourcesDirectory)/src/tests/Gopkg.lock'
      restoreKeys: |
        go | "$(Agent.OS)"
        go
      path: $(GO_CACHE_FOLDER)
    displayName: Cache Yarn packages
  - bash: dep ensure --vendor-only
    workingDirectory: $(Build.SourcesDirectory)/src/tests
    displayName: Retrieve Dependencies
    env:
      GOPATH: $(Build.SourcesDirectory)
  - bash: go test
    workingDirectory: $(Build.SourcesDirectory)/src/tests
    displayName: Testing the module
    env:
      GOPATH: $(Build.SourcesDirectory)
